services:
  pr-review-backend:
    build: ./pr-review-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://127.0.0.1:27017/pr-review-tool
      - JWT_SECRET=supersecretkey
      - GITHUB_TOKEN=your_github_personal_access_token
      - GITHUB_WEBHOOK_SECRET=webhooksecret
    volumes:
      - ./pr-review-backend:/app

  pr-review-frontend:
    build: ./pr-review-frontend
    ports:
      - "5173:5173"
    depends_on:
      - pr-review-backend
    volumes:
      - ./pr-review-frontend:/app
